logging:
    level:
        org:
            springframework:
                security: debug

server:
    port: 9991
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123
        url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
        username: root
    jackson:
        serialization:
            indent_output: true
mybatis-plus:
    global-config:
        db-config:
            logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
            logic-delete-value: 1 # 逻辑已删除值(默认为 1)
            logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl